insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (1, 59, 'PT', 'Trafaria');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (2, 97, 'SE', 'Solna');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (3, 66, 'CN', 'Wujing');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (4, 45, 'RU', 'Kosino');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (5, 54, 'CR', 'Heredia');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (6, 50, 'CN', 'Fuhai');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (7, 38, 'PL', 'Błonie');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (8, 91, 'PH', 'Bañga');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (9, 77, 'ID', 'Paobulan');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (10, 86, 'PL', 'Cielądz');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (11, 45, 'IT', 'Firenze');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (12, 78, 'BB', 'Four Cross Roads');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (13, 91, 'TH', 'Bang Krathum');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (14, 70, 'ID', 'Kebunkelapa');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (15, 19, 'RU', 'Verkhniye Achaluki');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (16, 7, 'CZ', 'Chlumec');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (17, 11, 'CN', 'Annan');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (18, 5, 'IT', 'Livorno');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (19, 96, 'FI', 'Tampere');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (20, 98, 'CO', 'Palmar de Varela');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (21, 29, 'CN', 'Yiqi');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (22, 82, 'PL', 'Piekoszów');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (23, 85, 'FR', 'Caen');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (24, 29, 'PT', 'Serra');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (25, 61, 'PH', 'Patrocinio');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (26, 54, 'IQ', 'Kirkuk');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (27, 80, 'NP', 'Dipayal');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (28, 100, 'BR', 'Jaguaribe');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (29, 96, 'ID', 'Krajan');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (30, 42, 'ID', 'Kaduela');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (31, 75, 'GR', 'Kaparéllion');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (32, 75, 'IR', 'Noşratābād');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (33, 33, 'PL', 'Bydgoszcz');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (34, 58, 'CM', 'Lagdo');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (35, 80, 'BG', 'Balgarevo');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (36, 23, 'CN', 'Fu’an');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (37, 28, 'RU', 'Rossosh’');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (38, 14, 'MN', 'Ongi');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (39, 58, 'CU', 'Calimete');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (40, 54, 'JP', 'Atami');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (41, 96, 'NO', 'Larvik');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (42, 87, 'CN', 'Baiyangwan');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (43, 6, 'CM', 'Fontem');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (44, 2, 'NO', 'Oslo');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (45, 90, 'CN', 'Zhufo');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (46, 94, 'CA', 'Millet');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (47, 18, 'US', 'Tulsa');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (48, 58, 'IL', 'Kefar Shemaryahu');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (49, 48, 'CN', 'Fulin');
insert into Aulas (Id_Aulas, Id_Asignatura, Capacidad, Material) values (50, 20, 'CN', 'Huangshanguan');
