insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (1, 'Reinaldo', 'Aaronson', 10, '3 Oakridge Center');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (2, 'Justinian', 'Santos', 4, '257 Buena Vista Road');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (3, 'Kerr', 'Ellicock', 39, '97 Pearson Point');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (4, 'Gwenore', 'Rappoport', 8, '17 Manitowish Junction');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (5, 'Dahlia', 'Page', 6, '091 Hansons Pass');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (6, 'Ignace', 'Hanford', 75, '1230 Sunbrook Place');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (7, 'Tabitha', 'Drewitt', 45, '3716 Wayridge Point');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (8, 'Juan', 'Carrel', 30, '684 6th Crossing');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (9, 'Bogey', 'Rackstraw', 90, '720 Graceland Hill');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (10, 'Pattin', 'Lagadu', 12, '4775 Coolidge Park');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (11, 'Winnie', 'Gofton', 56, '22 Loftsgordon Place');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (12, 'Derrek', 'Karpenko', 53, '3224 David Lane');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (13, 'Sherie', 'Rablen', 52, '18 Heath Pass');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (14, 'Tabbie', 'La Rosa', 82, '221 Toban Court');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (15, 'Dareen', 'Mewett', 49, '5 Dayton Terrace');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (16, 'Kirsteni', 'Bellee', 88, '517 Sunbrook Way');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (17, 'Annissa', 'Oldacres', 2, '80 Sachs Center');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (18, 'Cale', 'Ensor', 71, '48 Village Trail');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (19, 'Kelcey', 'Christophers', 71, '39670 Corscot Center');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (20, 'Kelcie', 'Greystoke', 53, '63 Donald Point');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (21, 'Lenette', 'Sealand', 80, '82353 Manitowish Drive');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (22, 'Clay', 'Kleinplac', 69, '51 Donald Pass');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (23, 'Michelle', 'Lambole', 22, '66 Ridgeview Court');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (24, 'Vivie', 'Flood', 61, '7245 Schmedeman Circle');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (25, 'Sela', 'Patriskson', 76, '1 Talmadge Court');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (26, 'Lorant', 'Bisiker', 13, '65435 Fair Oaks Road');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (27, 'Alejandro', 'Marages', 80, '1929 Susan Center');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (28, 'Roger', 'Ochterlony', 50, '711 Anhalt Center');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (29, 'Lisabeth', 'Sonley', 99, '33813 Victoria Alley');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (30, 'Rad', 'Calder', 15, '00 Chive Plaza');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (31, 'Donal', 'Jacobson', 79, '549 Oneill Junction');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (32, 'Francene', 'Kordas', 87, '2281 Anthes Circle');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (33, 'Jojo', 'Sykes', 49, '34766 South Court');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (34, 'Dotti', 'Deignan', 75, '02012 Pankratz Circle');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (35, 'Corty', 'Gwyllt', 58, '213 Moulton Road');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (36, 'Linn', 'Wetherill', 48, '69 Bashford Street');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (37, 'Anderea', 'Siddens', 94, '7 Gale Point');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (38, 'Elnore', 'Vignaux', 36, '68625 Maple Way');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (39, 'Perceval', 'Bartlet', 78, '9 Monica Way');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (40, 'Clio', 'Riccardelli', 98, '5 Bunker Hill Junction');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (41, 'Norine', 'Shurrocks', 29, '57 Veith Plaza');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (42, 'Nadeen', 'Cottill', 61, '46 Aberg Plaza');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (43, 'Rona', 'Bulleyn', 90, '36800 Manitowish Pass');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (44, 'Maryjo', 'Wandrey', 17, '3 Kennedy Point');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (45, 'Jennette', 'Pettegree', 38, '4 Gateway Alley');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (46, 'Roselin', 'Morrilly', 64, '8729 Pond Trail');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (47, 'Ashil', 'McAughtry', 5, '73 Pearson Alley');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (48, 'Ax', 'Parnall', 4, '74864 Glacier Hill Parkway');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (49, 'Gavan', 'Illiston', 94, '2 Laurel Crossing');
insert into Profesores (Id_Profesor, Nombre, Apellido, Telefono, Direccion) values (50, 'Craig', 'Batecok', 43, '7285 Moose Road');
